# Generated by Django 5.0.2 on 2024-02-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userregister', '0002_userinformation_delete_interestedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='carModel',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
