# Generated by Django 5.0.2 on 2024-02-25 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userregister', '0006_otp_generatetime_alter_otp_created_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='isused',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TestDriveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InterestedTestDriveCar', models.CharField(max_length=200)),
                ('dateOfTestDrive', models.DateTimeField()),
                ('timeOfTestDrive', models.TimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
