# Generated by Django 5.0.2 on 2024-02-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userregister', '0009_userinformation_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='reference',
        ),
    ]
