# Generated by Django 5.0.2 on 2024-02-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userregister', '0011_alter_testdrivedata_dateoftestdrive'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('isused', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='testdrivedata',
            name='phonenumber',
            field=models.BigIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testdrivedata',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
