version: '3.0'
services:
  frontend:
    build: ./BYD-Nepal-main
    container_name: byd_nepal_frontend
    image: byd_nepal_frontend
    environment:
      - DB_HOST=db
    command: sh -c "yarn run dev --host 0.0.0.0"
    ports:
      - 5173:5173
    expose:
      - 5173
    depends_on:
      - db
      - app
    links:
      - db:db

    networks:
        - byddjangonetwork
  app:
    build: ./Backend
    container_name: byd_nepal_backend
    image: byd_nepal_backend
    env_file:
      - ./Backend/.env
    environment:
      - DB_HOST=db
    command: sh -c "python3 manage.py migrate && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - byd_static:/adpp/BYDUsers/stacticfiles
    links:
      - db:db

    networks:
        - byddjangonetwork
  db:
    image: mysql:8
    container_name: byd_database
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: byd-pass
      MYSQL_DATABASE: byd-db
      MYSQL_USER: byd-user
      MYSQL_PASSWORD: byd-pass
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
        - byddjangonetwork


networks:
    byddjangonetwork:
        driver: bridge
volumes: 
  dbdata:
  byd_static:
  
  